const playersData = [
    {
        id: "01",
        name: "L. Messi",
        age: 31,
        nationality: "Argentina",
        overall: 94,
        club: "FC Barcelona",
        value: "110.5M",
        wage: "565k",
        preferred: "left",
        work_rate: "Medium/Medium",
        position: "RF",
        jersey_number: 10,
        joined: "1-jul-04",
        contract_valid_until: 2021,
        height: "5'7",
        weight: "159lbs",
        crossing: 84,
        finishing: 95,
        heading_accuracy: 70,
        short_passing: 90,
        vollays: 86
    },
        {
        id: "02",
        name: "Cristiano Ronaldo",
        age: 33,
        nationality: "Portugal",
        overall: 94,
        club: "Juventus",
        value: "77M",
        wage: "405k",
        preferred: "Right",
        work_rate: "High/Low",
        position: "ST",
        jersey_number: 7,
        joined: "10-jul-18",
        contract_valid_until: 2022,
        height: "6'2",
        weight: "183lbs",
        crossing: 84,
        finishing: 94,
        heading_accuracy: 89,
        short_passing: 81,
        vollays: 87
    },
        {
        id: "03",
        name: "Neymar Jr",
        age: 26,
        nationality: "Brazil",
        overall: 92,
        club: "Paris Saint-Germain",
        value: "118.5M",
        wage: "290k",
        preferred: "Right",
        work_rate: "Hight/Medium",
        position: "LW",
        jersey_number: 10,
        joined: "3-Aug-17",
        contract_valid_until: 2022,
        height: "5'9",
        weight: "150lbs",
        crossing: 79,
        finishing: 87,
        heading_accuracy: 62,
        short_passing: 84,
        vollays: 84
    },
        {
        id: "04",
        name: "De Gea",
        age: 27,
        nationality: "Spain",
        overall: 91,
        club: "Manchester United",
        value: "72M",
        wage: "260k",
        preferred: "Right",
        work_rate: "Medium/Medium",
        position: "GK",
        jersey_number: 1,
        joined: "1-jul-11",
        contract_valid_until: 2020,
        height: "6'4",
        weight: "168lbs",
        crossing: 17,
        finishing: 13,
        heading_accuracy: 21,
        short_passing: 50,
        vollays: 13
    },
        {
        id: "05",
        name: "K. De Bruyne",
        age: 27,
        nationality: "Belgium",
        overall: 91,
        club: "Manchester City",
        value: "102M",
        wage: "355k",
        preferred: "Right",
        work_rate: "Hight/Hight",
        position: "RCM",
        jersey_number: 7,
        joined: "########",
        contract_valid_until: 2023,
        height: "5'11",
        weight: "154lbs",
        crossing: 93,
        finishing: 82,
        heading_accuracy: 55,
        short_passing: 92,
        vollays: 82
    }
]

export default playersData;